core:
  # mastdon か misskey か pleroma(未実装)が選択可能 あとは知らん
  activitypub_software : misskey
  # 1回の学習時に食わせる投稿フェッチ回数(多分)
  source_activity_count: 200
  # モデル再生成を強制する(Lambda等one shot化されている場合に使用)
  force_remodel: true
read_mastdon:
  # リプライを除外
  exclude_replies : 1
  # ブーストを除外
  exclude_reblogs : 1
read_misskey:
  # リプライを除外
  includeReplies : false
  # リノートを除外
  includeMyRenotes : false
write_mastdon:
  # 公開範囲
  visibility : unlisted
write_misskey:
  # 公開範囲
  visibility : home